name: CI
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: windows-2019
    env:
      CCACHE_COMPRESS: true
      CCACHE_MAXSIZE: 500M
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.3.2
          arch: win64_msvc2019_64
          archives: qtbase qtsvg
          extra: --external 7z
      - name: Install dependencies for MSVC
        working-directory: ${{ runner.workspace }}
        run: |
          curl -L https://github.com/Kazfyx/rl-3rdparty/releases/download/latest/rl-3rdparty-msvc-14.2-x64.7z -o rl-3rdparty-msvc-14.2-x64.7z
          7z x rl-3rdparty-msvc-14.2-x64.7z -orl-install
          Write-Output "${{ runner.workspace }}\rl-install\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
      - name: Update environment variables
        run: |
          Write-Output "CCACHE_BASEDIR=${{ runner.workspace }}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "CCACHE_DIR=${{ runner.workspace }}\.ccache" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: Configure CMake
        run: >
          cmake
          -G"Visual Studio 16 2019" -A x64
          -DCMAKE_INSTALL_PREFIX="${{ runner.workspace }}/rl-install"
          -DRL_BUILD_TESTS=OFF
          -S"${{ github.workspace }}"
          -B"${{ runner.workspace }}/rl-build"
      - name: Build Debug
        working-directory: ${{ runner.workspace }}/rl-build
        run: cmake --build . --config Debug --target INSTALL
      - name: Build Release
        working-directory: ${{ runner.workspace }}/rl-build
        run: cmake --build . --config Release --target INSTALL
#      - name: Test
#        working-directory: ${{ runner.workspace }}/rl-build
#        run: ctest --output-on-failure
      - name: Create archive
        working-directory: ${{ runner.workspace }}/rl-build
        run: 7z a rl-install.7z "${{ runner.workspace }}/rl-install"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rl-windows-2019-msvc
          path: ${{ runner.workspace }}/rl-build/rl-install.7z
